const CONFIG = {
    maxHp: 3,
    scorePerData: 100,
    playerXRatio: 0.16,
    upperYRatio: 0.32,
    lowerYRatio: 0.68,
    playerMoveSpeed: 20,
    playerRadiusRatio: 0.027,
    playerCollisionScale: 0.84,
    minRadius: 11,
    dataRadiusRatio: 0.03,
    errorRadiusRatio: 0.034,
    glitchRadiusRatio: 0.03,

    /* All RUN MODE difficulty knobs live here. Bands lerp by survival time. */
    difficulty: {
        invertDuration: 1.55,
        wobbleLaneFraction: 0.11,
        minSwitchWindow: 0.28,
        bands: [
            {
                t: 0,
                scrollSpeed: 185,
                spawnGap: 1.55,
                altDelay: 0.64,
                doubleStagger: 0.58,
                fastMult: 1.26,
                minReaction: 1.2,
                dataBaitChance: 0.28,
                dataLead: 0.5,
                glitchChance: 0.0,
                weights: {
                    single: 78,
                    alt: 10,
                    reverseAlt: 8,
                    double: 0,
                    fast: 4,
                    wobble: 0,
                },
            },
            {
                t: 30,
                scrollSpeed: 235,
                spawnGap: 1.18,
                altDelay: 0.54,
                doubleStagger: 0.5,
                fastMult: 1.32,
                minReaction: 1.05,
                dataBaitChance: 0.36,
                dataLead: 0.46,
                glitchChance: 0.04,
                weights: {
                    single: 42,
                    alt: 22,
                    reverseAlt: 16,
                    double: 8,
                    fast: 8,
                    wobble: 4,
                },
            },
            {
                t: 60,
                scrollSpeed: 295,
                spawnGap: 0.94,
                altDelay: 0.44,
                doubleStagger: 0.44,
                fastMult: 1.4,
                minReaction: 0.92,
                dataBaitChance: 0.4,
                dataLead: 0.42,
                glitchChance: 0.06,
                weights: {
                    single: 22,
                    alt: 24,
                    reverseAlt: 18,
                    double: 14,
                    fast: 12,
                    wobble: 10,
                },
            },
            {
                t: 120,
                scrollSpeed: 355,
                spawnGap: 0.76,
                altDelay: 0.36,
                doubleStagger: 0.4,
                fastMult: 1.48,
                minReaction: 0.8,
                dataBaitChance: 0.42,
                dataLead: 0.38,
                glitchChance: 0.07,
                weights: {
                    single: 12,
                    alt: 22,
                    reverseAlt: 18,
                    double: 18,
                    fast: 16,
                    wobble: 14,
                },
            },
            {
                t: 180,
                scrollSpeed: 415,
                spawnGap: 0.62,
                altDelay: 0.32,
                doubleStagger: 0.38,
                fastMult: 1.55,
                minReaction: 0.72,
                dataBaitChance: 0.38,
                dataLead: 0.36,
                glitchChance: 0.08,
                weights: {
                    single: 8,
                    alt: 20,
                    reverseAlt: 16,
                    double: 20,
                    fast: 18,
                    wobble: 18,
                },
            },
        ],
    },
};
